image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - rust-lang.rust-analyzer

tasks:
  - name: Dependencies & Build
    init: |
      rustup target add wasm32-unknown-unknown &&
      cargo build
